### ISSUE TITLE
additional documentation

### ISSUE THREAD

**Issue by koron** [koron/vim#14]
「こういうときは見えなくなるよ」とかそういう注意事項・ノウハウ集を、ドキュメントに追記したほうが良さげ。

**Comment by mattn** [comment]
* 使用しているフォントに既に色無しの絵文字が含まれている場合には色は出ない
* 使用しているフォントに対象の絵文字が登録されていない場合はシステムがフォールバックする
* フォールバックされるデフォルト(シンボルフォント)によっては、固定幅以上の幅で描画される事がある(これは絵文字に関係なく起きる)

**Comment by mattn** [comment]
* Windows 10 標準では Segoe UI Symbols が、一部環境では Segoe UI Mono が絵文字のフォールバックとして使用される。
* Segoe UI Symbols は固定幅でない絵文字が含まれている

**Comment by koron** [comment]
* 一部フォント(ビットマップ埋め込みTTFフォント)は renmode:5,6 において描画されない

**Comment by koron** [comment]
* ~指定したフォントがDirectXから利用できないと代わりに `Courier_New:h12` が使われる。そのような事態に遭遇したら gfn や rop の設定を変更してくれ、と記載する。~

**Comment by koron** [comment]
> フォールバック時は速度が低下する

**Comment by koron** [comment]
書いたので閉じよう。
